### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by andyferriby** [tomhartnett/WatchList#1]
Trying to test the app and i get build failures with xcode.
Attached a screenshot from xcode
<img width="274" alt="Screenshot 2020-08-13 at 11 21 53" src="https://user-images.githubusercontent.com/21694968/90123830-57041500-dd57-11ea-95e1-d246d6cccec8.png">

**Comment by tomhartnett** [comment]
Are you building with Xcode 11.x?  I was able to reproduce your issue by building with Xcode 11.5.  I did not mention it in the readme, but I developed this with Xcode 12 beta.  I will update the readme.

**Comment by tomhartnett** [comment]
Readme updated.
